# Generated by Django 4.2.5 on 2023-09-22 00:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobbacoCRMapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
