# Generated by Django 4.2.5 on 2023-09-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobbacoCRMapi', '0005_seasonnames_bale_season_season_farmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bale',
            name='season',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='season',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Bale',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
