# Generated by Django 4.2.5 on 2023-09-24 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobbacoCRMapi', '0010_bales_balesqaulity'),
    ]

    operations = [
        migrations.AddField(
            model_name='balesqaulity',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='balesqaulity',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
