# Generated by Django 4.2.5 on 2023-09-24 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tobbacoCRMapi", "0013_season"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="emailAddress",
            new_name="email_address",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="firstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="lastName",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="phonenumber",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="postCode",
            new_name="post_code",
        ),
    ]
