# Generated by Django 4.2.5 on 2023-09-24 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tobbacoCRMapi", "0017_landtype_supplies_suppliestype_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractStatus",
        ),
        migrations.DeleteModel(
            name="Farmer",
        ),
        migrations.DeleteModel(
            name="FarmerStatus",
        ),
        migrations.DeleteModel(
            name="LandType",
        ),
        migrations.DeleteModel(
            name="Supplies",
        ),
        migrations.DeleteModel(
            name="SuppliesType",
        ),
    ]
