# Generated by Django 4.2.5 on 2023-09-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobbacoCRMapi', '0022_remove_images_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='thumbnail',
            new_name='medium',
        ),
    ]
