# Generated by Django 4.2.5 on 2023-09-26 19:19

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tobbacoCRMapi", "0023_delete_files_rename_thumbnail_images_medium"),
    ]

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(
                    default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
    ]
